[Eth]
NetworkId = 714
LightPeers = 100

[Eth.Miner]
GasCeil = 40000000
GasPrice = 1000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node]
DataDir = "node"
InsecureUnlockAllowed = false
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8575
HTTPVirtualHosts = ["*"]
HTTPModules = ["admin","personal","debug","eth", "net", "web3", "txpool",]
WSPort = 8576
WSModules = ["net", "web3", "eth"]


[Node.P2P]
MaxPeers = 50
NoDiscovery = false
TrustedNodes = []
StaticNodes = []


