[Eth]
NetworkId = 714
LightPeers = 100

[Eth.Miner]
GasCeil = 40000000
GasPrice = 1000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node]
DataDir = "node"
InsecureUnlockAllowed = false
IPCPath = "jumbo.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8575
HTTPVirtualHosts = ["*"]
HTTPModules = ["admin","personal","debug","eth", "net", "web3", "txpool",]
WSPort = 8576
WSModules = ["net", "web3", "eth"]


[Node.P2P]
MaxPeers = 50
NoDiscovery = false
TrustedNodes = []
StaticNodes = ["enode://d36d0a6b7504cc92e4f99f650848a50b66a29eb13bca97ee3d0f2b214560a9c187567a13971d9db1f5c859027b4ed66b80c17599eb4b52798e8ed3d809d3957b@127.0.0.1:0?discport=30305",
               "enode://f06b0393f5e927bb6a4fd31c2125db337facf32234cab52d3fc87c0c01431a8e72d4a0ed6f3c38a982fde190f2be4565e3076d2bdb5bcd34da4158e791da651b@127.0.0.1:0?discport=30305",
                ]


[Node.LogConfig]
FileRoot = ""
FilePath = "jumbo.log"
MaxBytesSize = 10485760
Level = "info"